### PR TITLE
Update Reviews.css / resolved font colour of reviews section in dark mode

### PR DESCRIPTION
**Pull request by dhairyagothi**

### CODE REVIEW

**Comment by Ayushhgupta39** [comment]
Can you add a image with the changes in effect?

**Comment by dhairyagothi** [comment]
> Can you add a image with the changes in effect?
> 

In testimonials ? 
I can try to do that

**Comment by Ayushhgupta39** [comment]
> > Can you add a image with the changes in effect?
> 
> In testimonials ? I can try to do that

No, just an image here for us to see your changes

**Comment by dhairyagothi** [comment]
> > > Can you add a image with the changes in effect?
> > 
> > In testimonials ? I can try to do that
> 
> No, just an image here for us to see your changes

Yes sure 
I have changed font colour of review section

**Comment by dhairyagothi** [comment]
please label this pr as gssoc @Ayushhgupta39

**Pull request merged**
