### PR TITLE
Implement Dark Mode Feature- Fixes #7

### LINKED ISSUE #7: [Feature to be added] Light/Dark Mode
A feature is to be added like that of full dark mode and light mode 

` a side nav button for toggling to light and dark`

Button Position: Right side,

Example:
image

Toggling button similar to this without Text inside the button.

### PR DESCRIPTION
**Pull request by Nishanth019**
**Issue**: Fixes #7

**Description**:
I've addressed issue #7 by implementing the dark mode feature. Here's what I did:

- Added a dark mode button.
- Implemented the functionality to toggle between light and dark modes.

I've created a video demonstration of these changes to provide a visual overview. You can watch the video here:

https://github.com/abhay-raj19/FitBody/assets/122528380/0b8d051f-5844-4de2-afd4-ffc260258426

I believe this change will enhance the user experience, and I hope you will consider merging it.

Please review and let me know if there are any further improvements needed. Thank you! @abhay-raj19

### CODE REVIEW

**Comment by abhay-raj19** [comment]
correct up the border of the `watch video` and  make them bit suitable for the dark mode and also make it bit curvy so that it perfectly aligh with the dark mode .

image

@Nishanth019 correct it up and I will  merge it , and will label it with hacktoberfest

**Comment by Nishanth019** [comment]
image

I think it is better now @abhay-raj19 sir. I raised this PR but it is not showing in my hactoberfest website as waiting. Actually I am new to hactober fest sir. It is showing that PR should be labelled as hactoberfest-accepted.

**Comment by Nishanth019** [comment]
@abhay-raj19 sir ?

**Comment by abhay-raj19** [comment]
make this watch video button like this @Nishanth019 
image


decrease the circle shape

**Comment by Nishanth019** [comment]
image

Modified watched video button sir. @abhay-raj19

**Pull request merged**
