### PR TITLE
Added Back button for navigation in classes

### PR DESCRIPTION
**Pull request by swetha5157**
Closes Issue: #294

### Description:
The navigation bar links issues in the "Get Started" page issue is solved by the inclusion of back to home button to facilitate users in returning to the main page issue is solved
Instead of nav bar links in the Get Started page, I've added the "Go to home" button from where we can access all those nav links.

**Test:**
I test the code, and there is no issue with this code.

**Screenshots/Video:**

https://github.com/abhay-raj19/FitBody/assets/123291594/fef91555-c22c-4369-9e9c-2ed3709ecee3

**I follow the Code of Conduct and Contributing Guidelines.**
**I am GSSoC'24 Contributor**

### CODE REVIEW

**Comment by swetha5157** [comment]
Raised PR kindly check it @abhay-raj19

**Comment by abhay-raj19** [comment]
UI doesn't matches with the UI of the application

**Comment by abhay-raj19** [comment]
and also improve up the button style little bit it not looks good though !

**Comment by swetha5157** [comment]
OK @abhay-raj19 , I'll make changes and raise new pr

**Pull request closed without merging**
