### PR TITLE
Reviews

### PR DESCRIPTION
**Pull request by dhruv8433**
@abhay-raj19 

- created review summery card
- merged men's and women's reviews

image

Responsive design looks like
image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@abhay-raj19  please check it and merge it

**Comment by abhay-raj19** [comment]
Looks good to me @dhruv8433 ✨

**Comment by abhay-raj19** [comment]
Just Resolve the Conflicts and all is fine

**Comment by abhay-raj19** [comment]
Those card can be equally divided i.e shadow same on both the sides.
Screenshot_2024-05-14-17-33-53-37_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by dhruv8433** [comment]
@abhay-raj19 ok i will do it

**Comment by dhruv8433** [comment]
@abhay-raj19  

### Shadow based on Swiper card lenght

it is swiper cards 
when we swipe, it create shadow on particular direction
i.e. if user swipe the 3 card in right direction then it display 3 shadows in right side...
based on quantity of our cards, it create shadow

image

**Pull request closed without merging**
