### PR TITLE
Added feature: new testimonial for mens

### PR DESCRIPTION
**Pull request by Faisalhs51**
Feat: #15 
Added new testimonial for mens
Both swiper component in the same container

image

<hr>

It is responsive also

image

### CODE REVIEW

**Comment by abhay-raj19** [comment]
Misaligment is there @Faisalhs51 

image

correct it Up.

**Comment by abhay-raj19** [comment]
there is still some misalingment in the swiper cards and minor issue in the navbar

image

**Comment by Faisalhs51** [comment]
Completed the changes
@abhay-raj19 please review it now

**Comment by abhay-raj19** [comment]
now it looks good @Faisalhs51 .

**Pull request merged**
