### PR TITLE
payment integration using razorpay

### PR DESCRIPTION
**Pull request by InshiyaRavat**
#102 issue reolved

### CODE REVIEW

**Comment by InshiyaRavat** [comment]
any update?

**Comment by abhay-raj19** [comment]
resolve the conflicts once will see to it next

**Comment by abhay-raj19** [comment]
Resolve up the conflicts

**Comment by InshiyaRavat** [comment]
I am working on it.

**Comment by InshiyaRavat** [comment]
Done. Please check

**Comment by abhay-raj19** [comment]
Pulled up the wrong branch

**Comment by InshiyaRavat** [comment]
I pulled your main branch.

**Pull request closed without merging**
