### PR TITLE
Cursorpointer/title cursor pointer pritam mukherjee

### PR DESCRIPTION
**Pull request by Pritam-2002**

### CODE REVIEW

**Comment by Pritam-2002** [comment]
i had made the signed off syntax although the ddco chek is failed please check it and also check the code i had changes and merge it under hacktoberfest 2023

**Comment by abhay-raj19** [comment]
@Pritam-2002 raising up the PR directly without raising out a prior issue into fitbody will not me merged .
Sorry but this is against the rules of Contributing into a project.

**Comment by Pritam-2002** [comment]
@abhay-raj19  #43 there is already a issue regarding this thats why  i made the pr

**Comment by abhay-raj19** [comment]
it was been already been raised up the @singhaman09

**Pull request closed without merging**
