### PR TITLE
After click on hamburger icons a box open up but after that cross icon should come in place of hamburger so user know to close that open box #302

### PR DESCRIPTION
**Pull request by kapilG0**
After click on hamburger icons a box open up but after that cross icon should come in place of hamburger so user know to close that open box #302
image

### CODE REVIEW

**Comment by kapilG0** [comment]
Hello @abhay-raj19 can you please check this pr

**Comment by abhay-raj19** [comment]
Resolve conflicts ASAP

**Comment by kapilG0** [comment]
> Resolve conflicts ASAP

Resolve conflicts please check @abhay-raj19

**Comment by kapilG0** [comment]
> > Resolve conflicts ASAP
> 
> Resolve conflicts please check @abhay-raj19

Hello @abhay-raj19 did you check that ?

**Comment by abhay-raj19** [comment]
Some of them are still pending up @kapilG0 
image

**Comment by kapilG0** [comment]
Hello @abhay-raj19 i have resolved all conflicts can you check ?

**Comment by abhay-raj19** [comment]
@kapilG0 So sorry for the delay , but your changes look good to me . 

Thanks for contributing to Fitbody

**Pull request merged**
