### PR TITLE
Added About Us Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #142 

Added the About Us Section and made it responsive as well

### CODE REVIEW

**Comment by Hemashree21** [comment]
@abhay-raj19 In the previous repo I wasn't able to resolve the conflicts so I deleted it and created a new one. Please merge it. 
Thankyou !

Screenshot 2024-05-13 180926

**Comment by Ayushhgupta39** [comment]
image
@abhay-raj19 Why is the routing removed from here?

**Comment by abhay-raj19** [comment]
@Ayushhgupta39 Who removed this though ?

**Comment by abhay-raj19** [comment]
thats why all the deployment are failing up

**Comment by Hemashree21** [comment]
> image @abhay-raj19 Why is the routing removed from here?
> 
> Also the deployment preview is not working. @Hemashree21 can you check this.

I'll check it 👍

**Comment by Hemashree21** [comment]
@abhay-raj19  @Ayushhgupta39  After I pulled the code when I run it, the output is showing a blank page like this. I tried debugging those errors but it's not working and I also tried commenting the code in which I made some changes. 

image

**Pull request closed without merging**
