### PR TITLE
Added validations using react-toastify

### PR DESCRIPTION
**Pull request by Niharika0104**
I have added validations using react-toastify

Additionally,I found that email sending login is missing.I have raised an issue for that #171 .Please assign me that issue I will fix it.Thanks.
contactform

### CODE REVIEW

**Comment by abhay-raj19** [comment]
Resolve conflict up pls as we have moved to vite that's why conflicts have been up due to the change in the name of file

**Comment by Niharika0104** [comment]
Okay I will resolve it

**Comment by Niharika0104** [comment]
@abhay-raj19  I resolved merge conflicts

**Comment by abhay-raj19** [comment]
but still they are pending to be resolved from your side it is showing me up
image

**Comment by Niharika0104** [comment]
Strange I will fix it

**Comment by Niharika0104** [comment]
@abhay-raj19 I have resolved all the merge conflicts

**Comment by abhay-raj19** [comment]
LGTM @Niharika0104

**Pull request merged**
