### PR TITLE
Enhancement-#198: Adding blur effect.

### LINKED ISSUE #198: Adding blur effect.
I want to add blur effect to the navbar, it'll look good with the project themes.

### PR DESCRIPTION
**Pull request by Mayur-666**
### Description:-

Added Blur effect ( glass-morphism to header). 
Also changed class to className at 2-3 places in Hero.jsx.

### Issue
Closes #198 

### Images:-
Screenshot (544)

Screenshot (545)

### CODE REVIEW

**Comment by Mayur-666** [comment]
@abhay-raj19  Are there any changes or suggestion ??

**Comment by abhay-raj19** [comment]
LGTM @Mayur-666 and also if possible pls remove that curvy border though

**Comment by abhay-raj19** [comment]
Not want this curvy line 
image

@Mayur-666 Pls resolve it asap

**Comment by Mayur-666** [comment]
@abhay-raj19  Sure i'll remove that border, but you have merged this PR. 
what should i do.

**Comment by Mayur-666** [comment]
@abhay-raj19  Should i Create another PR with no borders ??

**Pull request merged**
