### PR TITLE
Implemented the FAQ's section

### PR DESCRIPTION
**Pull request by DownOnCoffee**
This pull request introduces a new FAQ section to the website. The goal is to enhance user support by providing answers to common questions, thereby improving user experience.

Changes Made:
FAQ section: Created a new FAQ section accessible on main page. It includes categorized questions and answers.
Styling: Updated the CSS to match the existing design language of the website, ensuring a seamless user interface.

Screenshot (1299)
Screenshot (1300)

### CODE REVIEW

**Comment by DownOnCoffee** [comment]
@abhay-raj19  check this

**Comment by Ayushhgupta39** [comment]
@DownOnCoffee Resolve conflicts

**Comment by DownOnCoffee** [comment]
image
when I click on view build error i get 404 error thus I am not able to solve the issue. @Ayushhgupta39 @abhay-raj19

**Comment by DownOnCoffee** [comment]
@Ayushhgupta39 @abhay-raj19 Please help

**Comment by Ayushhgupta39** [comment]
Try to remove node_modules and package-lock.json on your end, take a pull, then npm install.

**Comment by DownOnCoffee** [comment]
@abhay-raj19 okay!

**Pull request closed without merging**
