### PR TITLE
Register/login page has been created 

### PR DESCRIPTION
**Pull request by kesharwaniyanshi**
Issue #332 
Register/login page has been created and links are attached . 
image
A similiar login page is made .But the pages are not connected to backend.
Also added a registered successfully and logged in successfully popups.

### CODE REVIEW

**Comment by Samani-Humaira** [comment]
Hey @abhay-raj19 ,

If all good can you please merge @kesharwaniyanshi #363 PR so that we can proceed with integrating the signup / login form with backend

**Comment by kesharwaniyanshi** [comment]
I made some more changes in this issue after sending PR , but the commits are not visible here. What should i do?

**Comment by kesharwaniyanshi** [comment]
image
image
This is how the pages look now.

**Comment by kesharwaniyanshi** [comment]
kindly review the pr and merge it

**Comment by abhay-raj19** [comment]
Resolve up the conflicts !!

**Comment by kesharwaniyanshi** [comment]
Resolved.

> Resolve up the conflicts !!

**Comment by kesharwaniyanshi** [comment]
Sir please merge the pr

**Comment by abhay-raj19** [comment]
LGTM @kesharwaniyanshi

**Pull request merged**
