### PR TITLE
GSSOC 24 | Added new page for workouts

### PR DESCRIPTION
**Pull request by satyam8932**
Add Feature/ New page with several workouts, instructions and videos where user can explore for free without creating account.

Click on get started of the classes section

### CODE REVIEW

**Comment by abhay-raj19** [comment]
Looks super Good just decrease a bit of content or make card looks less fill the content is too much .
and make that youtube video in center that is in the mid  right now the upper gap and lower gap is not same

**Comment by abhay-raj19** [comment]
Resolve all those conflits

**Comment by satyam8932** [comment]
Hi bro, I have made the changes and also tried to fix the conflicts but still it's showing me.
I also tried to install the necessary requirements but still it's not working and only admin can do it so please check it and merge it.
Also the changes are done you can check it.

Thanks
Satyam

**Comment by abhay-raj19** [comment]
> Hi bro, I have made the changes and also tried to fix the conflicts but still it's showing me. I also tried to install the necessary requirements but still it's not working and only admin have write access and can do it so please check it and merge it. Also the changes are done you can check it.
> 
> Thanks Satyam

What permissions are you talking about ?

**Comment by abhay-raj19** [comment]
From my side i also not have permissions to resolve those conflicts why so ?
image

some permission changes are required or somewhat else ?

**Pull request closed without merging**
