### PR TITLE
GSSOC 24 | Added new page for workouts

### PR DESCRIPTION
**Pull request by satyam8932**
Same PR again with same features but the conflict issues fixed

### CODE REVIEW

**Comment by satyam8932** [comment]
Hi @abhay-raj19 , I have created a new PR with the same code so that it don't have the conflict files error so please merge this issues and merge this code please.

Here is the New Issues https://github.com/abhay-raj19/FitBody/issues/180

Thanks

**Comment by abhay-raj19** [comment]
But this is to still showing me some of the conflicts though

**Comment by abhay-raj19** [comment]
conflicts to be resolved

**Comment by satyam8932** [comment]
well yesterday i pushed the code and it was working well without coflicts but looks like some of the folks have merge the code which changed everything that's why it's giving coflicts, ok this time i will create a PR but please merge it immediately otherwise someone's PR will again get merged and it will again give me conflicts due to file chagnes

Thanks

**Comment by satyam8932** [comment]
hey man now it's good please merge it otherwise someone will again come and do some shitt and it will again show conflict with the main code

**Comment by satyam8932** [comment]
image


See this

**Comment by abhay-raj19** [comment]
All conflict are resolved up now .
LGTM @satyam8932 
Thanks for contribution

**Comment by satyam8932** [comment]
Thanks @abhay-raj19 for giving me opportunity to contribute, I will try to create more features and implement in this project. :)

**Pull request merged**
