### PR TITLE
Contact form

### PR DESCRIPTION
**Pull request by dhruv8433**
- added contact form 
- update ui of contact form
- added react-hot-toast with validation
- update app.js

### CODE REVIEW

**Comment by dhruv8433** [comment]
@abhay-raj19 please check it and merge it

**Comment by abhay-raj19** [comment]
You showed me some UI but it is missing it is just the simple Contact Us form I want that form to be shifted bit right side and some UI at the left which makes it bit more attractive.

**Comment by dhruv8433** [comment]
ok got it i will do that side by side

**Comment by dhruv8433** [comment]
@abhay-raj19 
check out this
image

**Comment by dhruv8433** [comment]
@abhay-raj19 check the PR and please merge it

**Comment by abhay-raj19** [comment]
pls merge up the conflicts ASAP

**Pull request closed without merging**
