### PR TITLE
user, admin and plans backend done

### PR DESCRIPTION
**Pull request by ayann07**
I have added the user, admin and plans backend successfully and I have also checked all the functionalities using postman,
so issues #123  and #138 are now completed.
I have done this under GSSOC'24.

### CODE REVIEW

**Comment by ayann07** [comment]
I have now added the admin and plans backend aswell, so with this issue no. #138 is also completed.

**Comment by abhay-raj19** [comment]
Can you show me the same in a video rec format so that I can also sync those changes

**Comment by abhay-raj19** [comment]
and is there admin dashboard frontend been added up or only backend is there ?

**Comment by ayann07** [comment]
No frontend is not added, only backend is there. The plans can only be added by admin and even plans could be deleted by admin only,thats why admin dashboard would be needed .

**Comment by ayann07** [comment]
> Can you show me the same in a video rec format so that I can also sync those changes 

Sure, I'll do that.

**Comment by ayann07** [comment]
https://github.com/abhay-raj19/FitBody/assets/126085856/4cba94ea-d8be-4844-b0c3-7538dc930a4c

@abhay-raj19 you may check the functionality now.

**Comment by ayann07** [comment]
> Can you show me the same in a video rec format so that I can also sync those changes 

@abhay-raj19 please merge my pull request.

**Comment by ayann07** [comment]
@Ayushhgupta39 please see to it and approve these changes.

**Review by Ayushhgupta39 — APPROVED** [review]
LGTM.

**Comment by ayann07** [comment]
> LGTM.

Thankyou @Ayushhgupta39

**Comment by ayann07** [comment]
@abhay-raj19 please merge my pull request.

**Comment by abhay-raj19** [comment]
Look Awesome @ayann07 
Thank you so much for contributing into FitBody !!!
would be looking more from You 💙.

**Comment by ayann07** [comment]
> Look Awesome @ayann07 
> Thank you so much for contributing into FitBody !!!
> would be looking more from You 💙.

Thankyou @abhay-raj19 , definitely I'll contribute more✨

**Pull request merged**
