### PR TITLE
Testimonial Images changed

### PR DESCRIPTION
**Pull request by dhairyagothi**
As told testimonial images are changed please check and accept my PR request

### CODE REVIEW

**Comment by dhairyagothi** [comment]
please check and accept this PR @abhay-raj19 
so that i can move with other issues

**Comment by abhay-raj19** [comment]
The cards are not arranged up properly as the card in the women's section are not stacking up correctly

**Comment by dhairyagothi** [comment]
> The cards are not arranged up properly as the card in the women's section are not stacking up correctly

okay i will correct it and will make new PR

**Comment by abhay-raj19** [comment]
The old one looks Good though !!

**Pull request closed without merging**
