### PR TITLE
Added Legal Pages "Privacy Policy, Licensing, Terms and conditions" to the website 

### PR DESCRIPTION
**Pull request by MastanSayyad**
Fixes issue #285 

hey @abhay-raj19 and @Ayushhgupta39 I have added the dedicated pages for "Privacy Policy, Licensing, Terms and conditions" to the website and link to the footer so that users can that users can navigate to.

### Footer
image
### Privacy Policy
image
### Licensing
image
### Terms and Conditions
image

Please take a look and review it, Thank you!!

### CODE REVIEW

**Comment by Ayushhgupta39** [comment]
@MastanSayyad 

Why there is a copy file for the privacy policy component?
image

**Comment by MastanSayyad** [comment]
I might have copied it mistakenely while importing paths in App,jsx and CSS styles @Ayushhgupta39, as in my previous preview while committing I forgot sign my commit

**Comment by Ayushhgupta39** [comment]
@abhay-raj19 Can you check why the deployment preview is failing

**Comment by MastanSayyad** [comment]
I dont know why, but it's something related to vercel. Can you check the "Vercel Dashboard Logs" so that we can know the why this error occur. @Ayushhgupta39

**Comment by MastanSayyad** [comment]
Hey @abhay-raj19 could you please merge this PR

**Comment by abhay-raj19** [comment]
LGTM while it is working up in dev mode and not working in prod.

in dev :
if I visit localhost:5173/privacypolicy then it works but when I build up the project and then do serve in dist then it won't work 

can you check up @MastanSayyad @Ayushhgupta39

**Comment by MastanSayyad** [comment]
Hey @abhay-raj19, i have seen what you stated  but it is not my issue as I can see the legal pages on your deployed website, after clicking it is showing error 404 not found due to vercel routing navigation errod in vite framework. I will raise a new issue and PR regarding this please assign that to me (also please add the labels to this PR such as gssoc and levels). Thank you.

**Comment by Ayushhgupta39** [comment]
I guess the PR is already merged

**Comment by MastanSayyad** [comment]
@Ayushhgupta39 You havent add the labels to my this merged PR yet plss add labels

**Pull request merged**
