### PR TITLE
Added About Us Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #142 

Made it responsive.

image

Resolved all conflicts. Deployment link is working.
@abhay-raj19 @Ayushhgupta39 please check and merge it.

### CODE REVIEW

**Comment by Ayushhgupta39** [comment]
Great work @Hemashree21 !

**Comment by Hemashree21** [comment]
> Great work @Hemashree21 !

Thankyou! Can you please add level 1/level 2/level 3 label to this issue?

**Comment by Hemashree21** [comment]
@Ayushhgupta39 can you please assign level 2 for this PR, you had assigned it for the issue but it must be assigned for the PR as well

**Comment by sanjay-kv** [comment]
@Ayushhgupta39 Please assign the labels and add me into the repo

**Comment by sanjay-kv** [comment]
@MastanSayyad mail this admin , it seems like inactive

**Pull request merged**
